language: generic

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta
os:
  - linux
  - osx
  
notifications:
  email:
    on_success: never
    on_failure: change

script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

branches:
  only:
    - master

sudo: false

git:
  depth: 10
